/**
 * Auto-generated widget theme constants
 * Generated from src/styles/unistyles.ts
 *
 * DO NOT EDIT THIS FILE MANUALLY
 * Run: npm run generate-widget-theme
 */

export const WidgetColors = {
  text: '#ECEDEE',
  background: '#151718',
  tint: '#fff',
  icon: '#9BA1A6',
  tabIconDefault: '#9BA1A6',
  tabIconSelected: '#fff',
  border: '#2D3748',
  card: '#1F2937',
  error: '#EF4444',
  success: '#22C55E',
} as const;

export const WidgetSpacing = {
  xs: 4,
  sm: 8,
  md: 16,
  lg: 24,
  xl: 32,
  xxl: 48,
} as const;

export const WidgetFontSizes = {
  xs: 10,
  sm: 12,
  base: 14,
  md: 16,
  lg: 18,
  xl: 20
} as const;

export const WidgetBorderRadius = {
  sm: 4,
  md: 8,
  lg: 12,
  xl: 16,
  round: 999,
} as const;
